me = input()
name = input()
trt = round(int(me) / int(name))
print(trt)
hated_cartoon = input("Введите мультфильм, который вы ненавидите больше всего: ")
best_soccer_player = input("Введите имя лучшего футболиста, играющего в футбол: ")
favorite_mars_feature = input("Введите лучшее, что вам нравится на Марсе: ")
future_travel_country = input("Введите страну, в которую вы поедете в будущем: ")
future_car_count = input("Введите количество машин, которые у вас будет в будущем: ")
favorite_car_name = input("Введите название машины, которую вы любите больше всего: ")
num1 = int(11.2)
print(num1)
num2 = str(33)
print(num2)
num3 = str(90.90)
print(num3)
num4 = int(-12.12)
print(num4)
num5 = int("8899")
print(num5)
