spisok = []
spisok.append('narsa')
spisok.append('telefon')
spisok.append('air')
spisok.append('jordan')
spisok.append('kros')
spisok.insert(2, 'pods')
spisok.insert(3, 'noski')
spisok.insert(4, 'notebook')
spisok.insert(5, 'skobka')
spisok.insert(6, 'lochin')
spisok.remove('noski')
spisok.remove('notebook')
spisok.remove('air')
spisok.remove('pods')
spisok.remove('kros')
spisok.pop(4)
spisok.pop(1)
spisok.pop(3)
spisok.pop(1)
spisok.pop(3)

print(spisok)
